apply plugin: 'com.android.application'

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')

// Check if key.properties exists, then load it
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    namespace 'com.example.NotesNest'
    compileSdk 35

    buildFeatures {
        viewBinding true
    }

    signingConfigs {
        release {
            storeFile file(keystoreProperties['storeFile'] ?: 'key.properties')
            storePassword keystoreProperties['storePassword']
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
        }
    }

    defaultConfig {
        applicationId "com.hemanth.NotesNest"
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName "1.1.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            manifestPlaceholders = [usesCleartextTraffic: "false"]
        }
        debug {
            signingConfig signingConfigs.debug
            manifestPlaceholders = [usesCleartextTraffic: "true"]
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.work.runtime
    def room_version = "2.8.3"

    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"

    implementation "androidx.room:room-ktx:$room_version"

    implementation "androidx.webkit:webkit:1.14.0"

    implementation 'androidx.viewpager2:viewpager2:1.1.0'


    implementation 'com.google.firebase:firebase-core:9.6.1'

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation 'com.google.firebase:firebase-storage:22.0.0'
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation 'com.squareup.picasso:picasso:2.8'
    implementation 'com.google.firebase:firebase-database:22.0.0'
    implementation 'androidx.security:security-crypto:1.1.0-alpha03'
    implementation 'com.google.android.gms:play-services-auth:20.4.0'
    implementation 'com.google.firebase:firebase-auth:22.3.1'
    implementation 'com.google.android.gms:play-services-auth:21.2.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'com.facebook.shimmer:shimmer:0.5.0'

}

apply plugin: 'com.google.gms.google-services'
